## .vimrc
syntax on
set number
set relativenumber
set showcmd
set cursorline
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set wrap
set backspace=indent,eol,start
set clipboard=unnamed
set hlsearch
set incsearch
set laststatus=2
set ruler
colorscheme desert